/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as s1 from "./s1";
export type { s1 };
import type * as s2 from "./s2";
export type { s2 };
export type { RoyaltyDistributor } from "./RoyaltyDistributor";
