/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PotionLabV1__factory } from "./PotionLabV1__factory";
export { TestERC1155__factory } from "./TestERC1155__factory";
