/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as s1 from "./s1";
export * as s2 from "./s2";
export { RoyaltyDistributor__factory } from "./RoyaltyDistributor__factory";
